const options = {
  communityFeatures: [
      "Instant Messaging",
      "Voice/Video Chat",
      "Discussion Boards",
      "Content Sharing",
      "Live Streaming",
      "Other",
    ],
    communities: [
      "Artificial Intelligence",
      "Software Engineering",
      "Web Development",
      "Data Science",
      "Machine Learning",
      "Deep Learning",
      "Internet of Things",
      "Cloud Computing",
      "Cyber Security",
      "DevOps",
      "Blockchain Technology",
      "Augmented Reality",
      "Virtual Reality",
      "Game Development",
      "Mobile Development",
      "Frontend Development",
      "Backend Development",
      "Full Stack Development",
      "UI/UX Design",
      "Digital Marketing",
      "Graphic Design",
      "Video Editing",
      "Animation",
      "Blockchain Development",
      "Gaming",
      "Other",
    ],
    interactionFeatures: [
      "One-on-One Chats",
      "Video Calls",
      "Groups",
      "Forums",
      "Collaborative Workspaces",
      "Polls & Surveys",
      "Events",
      "Live Q&A Sessions",
      "Gamification",
      "Other",
    ],
    privacyFeatures: [
      "Private Conversations",
      "Control Over Notifications",
      "Anonymous Interactions",
      "Messages Available After Friend Request",
      "End-to-End Encryption",
      "Block or Mute Users",
      "Other",
    ],
    uxFeatures: [
      "Easy Navigation",
      "Fast Loading Times",
      "Customizable Themes",
      "Accessible & Intuitive Design",
      "Dark Mode",
      "Push Notifications",
      "Offline Mode",
      "Chatbots",
      "Voice Commands",
      "Hybrid Mode for Chat i.e., One-on-One, Group Chat & Interest Group Chat",
      "Other",
    ],
    contentConsumption: [
      "Text Posts",
      "Images",
      "Videos",
      "Live Streaming",
      "Discussions",
      "Tutorials & Mentoring",
      "Podcasts",
      "Webinars",
      "Courses",
      "Other",
    ],
    organizingFeatures: [
      "Event Scheduling",
      "Admin Tools",
      "Moderation Features",
      "Role Assignments & Analytics",
      "Group Rankings",
      "Guidelines",
      "Categories",
      "Search",
      "Recommendations",
      "Notifications",
      "Analytics",
      "Reports",
      "Feedback",
      "Polls",
      "Surveys",
      "Contests",
      "Rewards",
      "Recognition",
      "Challenges",
      "Meaningful Interactions",
      "Exclusive Content",
      "Other",
    ],
    motivations: [
      "Rewards",
      "Recognition",
      "Challenges",
      "Meaningful Interactions",
      "Exclusive Content",
      "Other",
    ],
  };

  export default options;